version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Starting build..."
      - curl ifconfig.me
      - curl checkip.amazonaws.com
      - wget -qO- http://checkip.amazonaws.com
      - codebuild-breakpoint
      - echo "This will run after resuming the build!!!"


artifacts:
  files:
    - '**/*'
